name: Code analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pycodestyle
      run: |
        pycodestyle *.py
    - name: Run pylint
      run: |
        pylint *.py
    - name: Run pytest
      run: |
        pytest
